using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using System.Collections.Generic;
using UnityEngine.SceneManagement;

public class CreateManager : MonoBehaviour
{
    [SerializeField] public Image[] peacePrefabs;  // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½ï¿½nï¿½u
    [SerializeField] private Transform canvas;      // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÌƒLï¿½ï¿½ï¿½ï¿½ï¿½oï¿½X
    [SerializeField] private Vector3 spawnPoints; // ï¿½ï¿½ï¿½ï¿½ï¿½Ê’u
    [SerializeField] private int SpwanFrame;        // ï¿½ï¿½ï¿½ï¿½ï¿½ÔŠu
    private int spawnTimer = 0;                     // ï¿½ï¿½ï¿½ï¿½ï¿½pï¿½^ï¿½Cï¿½}ï¿½[

    public ComboManager comboManager;
    public PieceManager2 pieceManager2;
    private ImageCheck ImageCheck;
    private SetZone SetZone;
    public int RandomImage;


    int combo = 0;

    void Start()
    {
        SetZone = FindObjectOfType<SetZone>();
        ImageCheck = FindObjectOfType<ImageCheck>();
        ShowImage();
    }

    void Update()
    {
        combo = comboManager.comboCount;

        // ï¿½Rï¿½ï¿½ï¿½{ï¿½ï¿½ï¿½20
        int effectiveCombo = Mathf.Min(combo, 20);

        spawnTimer++;

        // ï¿½ï¿½ï¿½ï¿½ï¿½ÔŠuï¿½ï¿½ï¿½Rï¿½ï¿½ï¿½{ï¿½É‰ï¿½ï¿½ï¿½ï¿½Ä’Zï¿½kï¿½iï¿½Åï¿½10ï¿½tï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½j
        int interval = Mathf.Max(10, SpwanFrame - effectiveCombo * 20);

        if (spawnTimer >= interval)
        {
            ShowImage();
        }
    }


    void ShowImage()
    {
        // ï¿½^ï¿½Cï¿½}ï¿½[ï¿½ï¿½ï¿½Zï¿½bï¿½g
        spawnTimer = 0;
        // ï¿½ï¿½ï¿½ï¿½ï¿½_ï¿½ï¿½ï¿½Èƒvï¿½ï¿½ï¿½nï¿½uï¿½ğ¶ï¿½
        RandomImage = Random.Range(0, peacePrefabs.Length);
        pieceManager2.SetPiece();
        Image image = Instantiate(peacePrefabs[RandomImage], canvas);
        ImageCheck.LeftImageNo(RandomImage); // ï¿½ï¿½ï¿½ï¿½ï¿½_ï¿½ï¿½ï¿½Åæ“¾ï¿½ï¿½ï¿½ï¿½ï¿½æ‘œï¿½Ôï¿½ï¿½ğ³Œë”»ï¿½ï¿½ÌƒXï¿½Nï¿½ï¿½ï¿½vï¿½gï¿½É“nï¿½ï¿½
        SetZone.RightImageTransForm(image); // ï¿½ï¿½ï¿½Wï¿½ï¿½nï¿½ï¿½
                                            // Imageï¿½ğ”½“]ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        Vector3 scale = image.rectTransform.localScale;
        image.rectTransform.localScale = new Vector3(-scale.x, scale.y, scale.z);
        // ï¿½ï¿½ï¿½ï¿½ï¿½Ê’uï¿½ï¿½İ’ï¿½
        image.transform.localPosition = spawnPoints;
    }

    public int ReturnRandomImage()
    {
        return RandomImage;
    }
}
